/**
 * Messaging App Filename Service
 *
 * Detects and extracts sequential ordering from filenames generated by
 * popular messaging apps (WhatsApp, Telegram, etc.)
 *
 * Supported patterns:
 *
 *  WhatsApp (Android):
 *    IMG-20260315-WA0001.jpg    → counter = 1
 *    IMG-20260315-WA0042.jpg    → counter = 42
 *    VID-20260315-WA0003.mp4    → counter = 3
 *
 *  WhatsApp (iOS):
 *    IMG_20260315_WA0001.jpg    → counter = 1
 *    Photo 15-03-2026, 14 30 01 (2).jpg → sequence = 2
 *
 *  Telegram:
 *    photo_2026-03-15_14-30-01.jpg         → timestamp-based
 *    photo_2026-03-15_14-30-01 (2).jpg     → sequence = 2
 *    document_2026-03-15_14-30-01.jpg      → timestamp-based
 *
 *  Generic messaging app patterns:
 *    image(1).jpg, image(2).jpg            → counter
 *    IMG_001.jpg, IMG_002.jpg              → counter
 *    received_1234567890.jpeg              → timestamp (epoch)
 *    signal-2026-03-15-143001.jpg          → timestamp
 *
 * The key insight: WhatsApp's WA#### counter is SEQUENTIAL per-day.
 * If all images share the same date prefix, the WA counter gives
 * the exact send/receive order.
 */

"use strict";

const path   = require("path");
const logger = require("../utils/logger");

// ── Pattern definitions ───────────────────────────────────────────────────────

/**
 * @typedef {Object} FilenameMatch
 * @property {string}  app          - Detected app name
 * @property {string}  pattern      - Pattern name that matched
 * @property {number}  sortKey      - Numeric key for sorting (counter or timestamp)
 * @property {string}  datePrefix   - Date part of filename (for grouping)
 * @property {number}  confidence   - 0.0–1.0
 */

const PATTERNS = [
  // ── WhatsApp Android: IMG-20260315-WA0001.jpg ──────────────────────────
  {
    name:   "whatsapp_android",
    app:    "WhatsApp",
    // Matches: IMG-YYYYMMDD-WA####.ext or VID-YYYYMMDD-WA####.ext
    regex:  /^(?:IMG|VID|AUD|STK|DOC|PTT)[-_](\d{8})[-_]WA(\d{4,5})\b/i,
    extract: (m) => ({
      datePrefix: m[1],
      sortKey:    parseInt(m[2], 10),  // WA counter — this is the gold!
      confidence: 0.95,
    }),
  },

  // ── WhatsApp iOS: sometimes different format ───────────────────────────
  {
    name:   "whatsapp_ios",
    app:    "WhatsApp",
    // Matches: Photo DD-MM-YYYY, HH MM SS.ext or with (N) suffix
    regex:  /^Photo\s+(\d{1,2}[-_.]\d{1,2}[-_.]\d{2,4}),?\s*(\d{1,2})\s+(\d{1,2})\s+(\d{1,2})(?:\s*\((\d+)\))?\b/i,
    extract: (m) => {
      const datePart = m[1].replace(/[-.]/g, "");
      const h = m[2].padStart(2, "0");
      const min = m[3].padStart(2, "0");
      const s = m[4].padStart(2, "0");
      const suffix = m[5] ? parseInt(m[5], 10) : 0;
      // Sort by time + suffix
      const timeKey = parseInt(`${h}${min}${s}`, 10) * 100 + suffix;
      return {
        datePrefix: datePart,
        sortKey:    timeKey,
        confidence: 0.88,
      };
    },
  },

  // ── Telegram: photo_YYYY-MM-DD_HH-MM-SS.jpg ───────────────────────────
  {
    name:   "telegram",
    app:    "Telegram",
    // Matches: photo_YYYY-MM-DD_HH-MM-SS.ext or document_... or video_...
    regex:  /^(?:photo|document|video|file)[-_](\d{4}[-_]\d{2}[-_]\d{2})[-_](\d{2})[-_](\d{2})[-_](\d{2})(?:\s*\((\d+)\))?\b/i,
    extract: (m) => {
      const datePart = m[1].replace(/[-_]/g, "");
      const h = m[2], min = m[3], s = m[4];
      const suffix = m[5] ? parseInt(m[5], 10) : 0;
      const timeKey = parseInt(`${h}${min}${s}`, 10) * 100 + suffix;
      return {
        datePrefix: datePart,
        sortKey:    timeKey,
        confidence: 0.90,
      };
    },
  },

  // ── Signal: signal-YYYY-MM-DD-HHMMSS.jpg ───────────────────────────────
  {
    name:   "signal",
    app:    "Signal",
    regex:  /^signal[-_](\d{4}[-_]\d{2}[-_]\d{2})[-_](\d{6})\b/i,
    extract: (m) => ({
      datePrefix: m[1].replace(/[-_]/g, ""),
      sortKey:    parseInt(m[2], 10),
      confidence: 0.88,
    }),
  },

  // ── Generic: image(1).jpg, IMG_001.jpg, photo_001.jpg ──────────────────
  {
    name:   "generic_counter",
    app:    "Messaging App",
    // Matches: anything_NNN.ext where NNN is 1-5 digits at the end of stem
    // But only if the prefix is a common image prefix
    regex:  /^(?:image|img|photo|pic|received|download|media)[-_. ]?\(?(\d{1,5})\)?$/i,
    extract: (m) => ({
      datePrefix: "generic",
      sortKey:    parseInt(m[1], 10),
      confidence: 0.75,
    }),
  },

  // ── Received files with epoch timestamps ───────────────────────────────
  {
    name:   "epoch_timestamp",
    app:    "Messaging App",
    regex:  /^(?:received|media|temp)[-_](\d{10,13})\b/i,
    extract: (m) => {
      let ts = parseInt(m[1], 10);
      if (ts > 1e12) ts = Math.floor(ts / 1000); // ms → s
      return {
        datePrefix: "epoch",
        sortKey:    ts,
        confidence: 0.80,
      };
    },
  },
];

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Attempt to detect messaging-app filename patterns across all files.
 * Returns a sort result if a consistent pattern is found.
 *
 * @param {Array<{ originalName: string, [key: string]: any }>} analyses
 * @returns {{ sortedImages: Array, sortMethod: string, sortMethodDescription: string } | null}
 */
function detectMessagingAppOrder(analyses) {
  if (!analyses || analyses.length < 2) return null;

  const n       = analyses.length;
  const matches = [];

  // ── Try to match each filename against all patterns ────────────────────
  for (let i = 0; i < n; i++) {
    const name = _stemName(analyses[i].originalName || "");
    let matched = false;

    for (const pat of PATTERNS) {
      const m = name.match(pat.regex);
      if (m) {
        const result = pat.extract(m);
        matches.push({
          imgIdx:     i,
          app:        pat.app,
          pattern:    pat.name,
          sortKey:    result.sortKey,
          datePrefix: result.datePrefix,
          confidence: result.confidence,
        });
        matched = true;
        break; // first matching pattern wins
      }
    }

    if (!matched) {
      matches.push(null);
    }
  }

  // ── Check if we have enough matches from the SAME pattern ──────────────
  const validMatches = matches.filter(Boolean);
  if (validMatches.length < n * 0.7) {
    logger.debug(`Messaging filename: only ${validMatches.length}/${n} matched — not enough.`);
    return null;
  }

  // All must be from the same pattern
  const patternCounts = {};
  for (const m of validMatches) {
    patternCounts[m.pattern] = (patternCounts[m.pattern] || 0) + 1;
  }

  const bestPattern = Object.entries(patternCounts).sort((a, b) => b[1] - a[1])[0];
  if (!bestPattern || bestPattern[1] < n * 0.7) {
    logger.debug("Messaging filename: no consistent pattern found.");
    return null;
  }

  const patternName    = bestPattern[0];
  const patternMatches = validMatches.filter((m) => m.pattern === patternName);

  // ── Check for unique sort keys (no duplicates) ─────────────────────────
  const sortKeys = patternMatches.map((m) => m.sortKey);
  const uniqueKeys = new Set(sortKeys);
  if (uniqueKeys.size < patternMatches.length * 0.8) {
    logger.debug("Messaging filename: too many duplicate sort keys.");
    return null;
  }

  // ── For WhatsApp: check that all share the same date prefix ────────────
  if (patternName.startsWith("whatsapp")) {
    const datePrefixes = new Set(patternMatches.map((m) => m.datePrefix));
    if (datePrefixes.size > 2) {
      // More than 2 different dates — might span multiple days, still ok
      // but lower confidence
      logger.debug(`Messaging filename: WhatsApp images span ${datePrefixes.size} dates.`);
    }
  }

  // ── Build sorted result ────────────────────────────────────────────────
  const withKey    = [];
  const withoutKey = [];

  for (let i = 0; i < n; i++) {
    const m = matches[i];
    if (m && m.pattern === patternName) {
      withKey.push({ img: analyses[i], sortKey: m.sortKey, match: m });
    } else {
      withoutKey.push(analyses[i]);
    }
  }

  // Sort by the extracted key
  withKey.sort((a, b) => a.sortKey - b.sortKey);
  withoutKey.sort((a, b) => a.originalIndex - b.originalIndex);

  const appName    = patternMatches[0].app;
  const avgConf    = patternMatches.reduce((s, m) => s + m.confidence, 0) / patternMatches.length;
  const keyRange   = `${withKey[0].sortKey}–${withKey[withKey.length - 1].sortKey}`;

  logger.info(
    `Messaging filename: detected ${appName} pattern "${patternName}" ` +
    `(${patternMatches.length}/${n} files, keys: ${keyRange}, confidence: ${avgConf.toFixed(2)})`
  );

  return {
    sortedImages: [...withKey.map((e) => e.img), ...withoutKey],
    sortMethod:   "messaging_app_filename",
    sortMethodDescription:
      `Sorted by ${appName} filename sequence (pattern: ${patternName}, ` +
      `${patternMatches.length} files matched, keys: ${keyRange}).` +
      (withoutKey.length > 0 ? ` ${withoutKey.length} unmatched file(s) appended.` : ""),
  };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Get filename stem (without extension).
 */
function _stemName(filename) {
  return path.basename(filename, path.extname(filename));
}

module.exports = { detectMessagingAppOrder };
